### ISSUE TITLE
gimp fails to start on Linux with theme applied

### ISSUE THREAD

**Issue by jeancf** [draekko/gimp-cc-themes#1]
Tried in on Mint (Ubuntu derivative) and Arch.

**Comment by draekko** [comment]
I don't maintain them anymore, i've put all of my energy on the upcoming 2.10 versions (you can test them out by self compiling the latest GIMP version from git on the master branch as they are now included by default with GIMP). 

Having said that you haven't provided enough information to be able to fix anything. I just tried this under Ubuntu and it works fine there. What version of gimp? was it self compiled or was it an OS supplied version? What does the log output say from gimp say?

For compiling GIMP from git sources visit https://www.gimp.org/source/howtos/gimp-git-build.html  & http://wiki.gimp.org/wiki/Hacking:Building

Or with Ubuntu get the ppa gimp-edge, https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/gimp-edge (they should have the light and darker versions in those) and upcoming versions will contain all five (as of yesterday).

You can find the new 2.9/2.10 versions independently for now here as well at https://github.com/draekko-rand/gimp-themes

**Comment by jeancf** [comment]
Thanks for your detailed response.

I have 2.8.16 installed using distribution binaries.
I don't know where to find the gimp log file but I ran it from the command line and it helped me find the problem: the packages are missing a dependency on `libopenraw`. I installed the library separately and the themes work now.
