### ISSUE TITLE
crashes when applying theme then uses default

### ISSUE THREAD

**Issue by awesomeness872** [draekko/gimp-cc-themes#3]
When I apply the theme GIMP crashes and when I open it it's the default theme. GIMP 2.8 w/ Linux mint

**Comment by draekko** [comment]
I just tried it with 2.8.18 and it works fine here. I would need to see the log output when starting from a terminal. Note that i don't really support this theme anymore as gimp 2.9 is stable enough all of my efforts go updating that. For the log do something like:

gimp-2.8 &> gimp.log

Then either attach the log or post it to pastebin.
