### ISSUE TITLE
On retina screen icons looks blurry #bug

### ISSUE THREAD

**Issue by reatlat** [draekko/gimp-cc-themes#6]
TY for amazing dark themes for GIMP,
On MacBook pro 2017 with IPS screen icons looks blurry,
I think we have to use double pixel sizes for icons.

TY for good work.

**Comment by draekko** [comment]
Thank you. Yes it probably requires the changes that you described. Unfortunately i no longer offer support for them as they are now part of GIMP as of version 2.9.2. While i might be interested in figuring it out i do not own a monitor with such resolutions so i doubt i could make the necesseray changes. If you feel like providing  a patched version with the required changes i would be open to creating a new branch for them.
